### ISSUE TITLE
data(cpsvote::cps_sample_10k) doesn't work for me even though I have that data

### ISSUE THREAD

**Issue by paulgronke** [Reed-EVIC/cpsvote#20]
```
> data(cpsvote::cps_sample_10k)
Warning message:
In data(cpsvote::cps_sample_10k) :
  data set ‘cpsvote::cps_sample_10k’ not found
```

**Comment by jayleetx** [comment]
This comes from the behavior of `data`. The syntax should be `data(cps_sample10k, package = "cpsvote")`, to stick it into your environment. The double-colon access doesn't work inside of this function, because internally it's transforming the supplied name into a character and looping through the package stack to find that specific data set's name (which will lack the package specifier, since it's already inside of the package).
